-- Auto-generated by scripts/check-ef-baseline.ps1
-- Purpose: align __EFMigrationsHistory with source migrations without rerunning DDL
BEGIN;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20251204053233_SyncSnapshot', '8.0.0'
WHERE NOT EXISTS (
  SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251204053233_SyncSnapshot'
);
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260215120655_SeedDrillTypesData', '8.0.0'
WHERE NOT EXISTS (
  SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215120655_SeedDrillTypesData'
);
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260215131341_SeedSampleDrillSchedules', '8.0.0'
WHERE NOT EXISTS (
  SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215131341_SeedSampleDrillSchedules'
);
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260318023028_AddSyncStateTable', '8.0.0'
WHERE NOT EXISTS (
  SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260318023028_AddSyncStateTable'
);
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260322095525_AddMetadataFirstFileSyncPhase1', '8.0.0'
WHERE NOT EXISTS (
  SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260322095525_AddMetadataFirstFileSyncPhase1'
);
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260322120804_AddSyncFileChunkSessionsPhase3', '8.0.0'
WHERE NOT EXISTS (
  SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260322120804_AddSyncFileChunkSessionsPhase3'
);
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260322135457_AddSyncTransferOptimizations', '8.0.0'
WHERE NOT EXISTS (
  SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260322135457_AddSyncTransferOptimizations'
);
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260322141855_FixSyncTransferSchemaDrift', '8.0.0'
WHERE NOT EXISTS (
  SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260322141855_FixSyncTransferSchemaDrift'
);
COMMIT;
