# =====================================================
# STEP 4: FINALIZE RESET
# Create distribution package for team
# =====================================================

$ErrorActionPreference = "Stop"
$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"

Write-Host "================================" -ForegroundColor Cyan
Write-Host "STEP 4: FINALIZE & PACKAGE" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan
Write-Host ""

# ===== VERIFICATION =====
Write-Host "Verifying migration reset..." -ForegroundColor Yellow

$isValid = $true

# Check migrations folder
$migrationsFolder = ".\Data\Migrations"
if (Test-Path $migrationsFolder) {
    $migrations = Get-ChildItem $migrationsFolder -Filter "*.cs"
    $migCount = ($migrations | Measure-Object).Count
    
    # Should have exactly one migration (2 files: .cs and .Designer.cs, plus EdgeDbContextModelSnapshot.cs)
    if ($migCount -eq 3) {
        Write-Host "  [OK] Clean migration state ($migCount files)" -ForegroundColor Green
        
        $hasInitial = $migrations | Where-Object { $_.Name -like "*InitialCreate_Clean*" }
        if ($hasInitial) {
            Write-Host "  [OK] InitialCreate_Clean migration found" -ForegroundColor Green
        }
        else {
            Write-Host "  [WARN] Migration doesn't match expected name" -ForegroundColor Yellow
        }
    }
    else {
        Write-Host "  [WARN] Expected 3 migration files, found $migCount" -ForegroundColor Yellow
        $isValid = $false
    }
}
else {
    Write-Host "  [ERROR] Migrations folder not found" -ForegroundColor Red
    $isValid = $false
}

# Build test
Write-Host "  - Testing build..." -ForegroundColor DarkGreen
dotnet build --no-incremental 2>&1 | Out-Null
if ($LASTEXITCODE -eq 0) {
    Write-Host "  [OK] Build successful" -ForegroundColor Green
}
else {
    Write-Host "  [ERROR] Build failed" -ForegroundColor Red
    $isValid = $false
}

Write-Host ""

if (-not $isValid) {
    Write-Host "[ERROR] Validation failed. Please fix issues before finalizing." -ForegroundColor Red
    Write-Host "You can run '.\3-restore-backup.ps1' to rollback" -ForegroundColor Yellow
    exit 1
}

# ===== CREATE DISTRIBUTION PACKAGE =====
Write-Host "Creating distribution package for team..." -ForegroundColor Yellow

$distFolder = ".\migration-reset-package-$timestamp"
New-Item -ItemType Directory -Path $distFolder | Out-Null

# 1. Export clean database
Write-Host "  - Exporting clean database..." -ForegroundColor DarkGreen
$dbExportFile = Join-Path $distFolder "maritime_edge_CLEAN_$timestamp.sql"
$containerName = "maritime-edge-postgres"
$dbUser = "edge_user"
$dbName = "maritime_edge"

docker exec $containerName pg_dump -U $dbUser -d $dbName > $dbExportFile
$dbSize = (Get-Item $dbExportFile).Length / 1MB
Write-Host "    Database exported: $([math]::Round($dbSize, 2)) MB" -ForegroundColor Green

# 2. Create team migration guide
Write-Host "  - Creating migration guide..." -ForegroundColor DarkGreen

$guideContent = @"
# 🔄 Migration Reset Guide - Team Setup

**Date:** $(Get-Date -Format "yyyy-MM-dd HH:mm")
**Generated by:** Migration Reset Scripts

## ⚠️ IMPORTANT - READ FIRST

This package contains:
1. Clean database backup (maritime_edge_CLEAN_$timestamp.sql)
2. New baseline migration (already in code)
3. Setup instructions (this file)

## 📋 Prerequisites

- Docker Desktop running
- Git installed
- .NET 8 SDK installed
- Access to repository

## 🚀 Setup Steps

### Step 1: Backup Your Current Work

**CRITICAL:** Save any local changes first!

``````powershell
# Commit any work in progress
git add .
git commit -m "WIP: before migration reset"
``````

### Step 2: Pull Latest Code

``````powershell
# Make sure you're on the correct branch
git checkout [branch-name]

# Pull latest code with migrations
git pull origin [branch-name]
``````

### Step 3: Stop & Clean Docker

``````powershell
# Stop containers
docker-compose down

# Remove old volume (WARNING: DATA LOSS!)
docker volume rm maritime-edge-postgres-data

# Start fresh
docker-compose up -d
``````

Wait 10-15 seconds for database to initialize.

### Step 4: Restore Clean Database

``````powershell
# Navigate to edge-services folder
cd edge-services

# Copy database backup to container
docker cp migration-reset-package-$timestamp\maritime_edge_CLEAN_$timestamp.sql maritime-edge-postgres:/tmp/restore.sql

# Restore database
docker exec maritime-edge-postgres psql -U edge_user -d maritime_edge -f /tmp/restore.sql
``````

### Step 5: Verify Setup

``````powershell
# Check migrations
dotnet ef migrations list --context EdgeDbContext

# Should show only:
# - InitialCreate_Clean (Applied)

# Build project
dotnet build

# Run application
dotnet run
``````

### Step 6: Test Application

1. Open browser: http://localhost:5005
2. Check database tables exist
3. Try basic operations

## ✅ Verification Checklist

- [ ] Git pull completed successfully
- [ ] Docker containers running
- [ ] Database restored (no errors)
- [ ] Only 1 migration shows in migrations list
- [ ] Build successful (no errors)
- [ ] Application runs without errors
- [ ] Can access database and view data

## 🆘 Troubleshooting

### Issue: "Migration already applied"

``````powershell
# Clear migration history and reapply
docker exec maritime-edge-postgres psql -U edge_user -d maritime_edge -c "DELETE FROM \"__EFMigrationsHistory\";"
dotnet ef database update
``````

### Issue: "Connection refused"

``````powershell
# Check container is running
docker ps | grep maritime-edge-postgres

# Check logs
docker logs maritime-edge-postgres
``````

### Issue: Build errors

``````powershell
# Clean and rebuild
dotnet clean
dotnet build --no-incremental
``````

## 📞 Support

If you encounter issues:
1. Check this guide's troubleshooting section
2. Ask in team chat with error message
3. Don't modify database manually

## 🎯 Rules Going Forward

**IMPORTANT - FOLLOW THESE RULES:**

### ✅ DO:
- Always use EF migrations for schema changes
- Pull latest code before making changes
- Run ``dotnet ef database update`` after pulling
- Commit migrations with related code

### ❌ DON'T:
- Run SQL scripts directly on database (except data seeding)
- Modify migration files manually
- Delete migrations without team discussion

### Migration Workflow:

``````powershell
# 1. Make model changes in code
# 2. Create migration
dotnet ef migrations add [DescriptiveName]

# 3. Review generated migration file
# 4. Apply to local database
dotnet ef database update

# 5. Test thoroughly
# 6. Commit both code and migration
git add .
git commit -m "feat: add new feature (with migration)"
git push
``````

## 📊 Package Contents

- ``maritime_edge_CLEAN_$timestamp.sql`` - Clean database backup
- ``MIGRATION_GUIDE.md`` - This file
- ``package-info.json`` - Metadata

---

**Questions?** Contact team lead or check documentation.
"@

$guideFile = Join-Path $distFolder "MIGRATION_GUIDE.md"
$guideContent | Out-File $guideFile -Encoding UTF8
Write-Host "    Migration guide created" -ForegroundColor Green

# 3. Create package info
$packageInfo = @{
    CreatedDate = $timestamp
    DatabaseFile = "maritime_edge_CLEAN_$timestamp.sql"
    DatabaseSize = "$([math]::Round($dbSize, 2)) MB"
    MigrationName = "InitialCreate_Clean"
    Instructions = "See MIGRATION_GUIDE.md"
} | ConvertTo-Json

$infoFile = Join-Path $distFolder "package-info.json"
$packageInfo | Out-File $infoFile -Encoding UTF8
Write-Host "    Package info created" -ForegroundColor Green

Write-Host ""
Write-Host "  [OK] Distribution package created" -ForegroundColor Green
Write-Host ""

# ===== GIT COMMANDS SUGGESTION =====
Write-Host "Suggested Git commands:" -ForegroundColor Yellow
Write-Host ""
Write-Host "  # Add migrations" -ForegroundColor DarkGray
Write-Host "  git add Data/Migrations/" -ForegroundColor Cyan
Write-Host ""
Write-Host "  # Commit" -ForegroundColor DarkGray
Write-Host "  git commit -m `"chore: reset migrations to clean baseline`"" -ForegroundColor Cyan
Write-Host ""
Write-Host "  # Push to remote" -ForegroundColor DarkGray
Write-Host "  git push origin [your-branch]" -ForegroundColor Cyan
Write-Host ""

# ===== SUCCESS =====
Write-Host "================================" -ForegroundColor Green
Write-Host "MIGRATION RESET FINALIZED" -ForegroundColor Green
Write-Host "================================" -ForegroundColor Green
Write-Host ""
Write-Host "✅ All steps completed successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Distribution package location:" -ForegroundColor Cyan
Write-Host "  $distFolder" -ForegroundColor White
Write-Host ""
Write-Host "Package contents:" -ForegroundColor Cyan
Get-ChildItem $distFolder | ForEach-Object {
    $size = if ($_.PSIsContainer) { "" } else { " ($([math]::Round($_.Length/1MB, 2)) MB)" }
    Write-Host "  - $($_.Name)$size" -ForegroundColor White
}
Write-Host ""
Write-Host "NEXT STEPS:" -ForegroundColor Yellow
Write-Host "1. Review migration files in Data/Migrations/" -ForegroundColor White
Write-Host "2. Commit and push to Git (see commands above)" -ForegroundColor White
Write-Host "3. Share package with team:" -ForegroundColor White
Write-Host "   - Upload to shared drive/cloud" -ForegroundColor DarkGray
Write-Host "   - Or commit database backup to Git (if not too large)" -ForegroundColor DarkGray
Write-Host "4. Team follows MIGRATION_GUIDE.md to sync" -ForegroundColor White
Write-Host ""
Write-Host "Backup location (in case of issues):" -ForegroundColor Yellow
if (Test-Path ".\last-backup-path.txt") {
    $backupLoc = Get-Content ".\last-backup-path.txt"
    Write-Host "  $backupLoc" -ForegroundColor DarkGray
}
Write-Host ""
