using System.ComponentModel.DataAnnotations;

namespace Maritime.Shared.Models.Sync;

/// <summary>
/// Sync action types for delta sync protocol
/// </summary>
public enum SyncActionType
{
    CREATE = 0,
    UPDATE = 1,
    DELETE = 2,
    SNAPSHOT = 3
}

/// <summary>
/// Priority levels for network-aware sync
/// </summary>
public enum SyncPriority
{
    Critical = 1,    // P1: Distress, Safety Alarms → immediate (Iridium OK)
    Operational = 2, // P2: Noon Report, Position → scheduled batch (VSAT+)
    Low = 3          // P3: Crew logs, Inventory → bandwidth permitting (4G/WiFi)
}

/// <summary>
/// Network connection types available on vessel
/// </summary>
public enum NetworkType
{
    None = 0,
    Satellite_Iridium = 1,
    Satellite_VSAT = 2,
    Cellular_4G = 3,
    Shore_WiFi = 4
}

/// <summary>
/// File transfer lifecycle status for metadata-first sync.
/// </summary>
public enum SyncFileTransferStatus
{
    MetadataOnly = 0,
    Requested = 1,
    Verified = 2,
    Duplicate = 3,
    Failed = 4,
    Cancelled = 5
}

/// <summary>
/// Status of a file transfer request generated by the receiving node.
/// </summary>
public enum SyncFileRequestStatus
{
    Pending = 0,
    Deferred = 1,
    Completed = 2,
    Failed = 3,
    Cancelled = 4
}

/// <summary>
/// Lifecycle of a resumable chunk transfer session.
/// </summary>
public enum SyncFileChunkSessionStatus
{
    Pending = 0,
    Active = 1,
    Completed = 2,
    Failed = 3,
    Cancelled = 4,
    Expired = 5
}

/// <summary>
/// Transport encoding used when shipping file bytes over the sync channel.
/// </summary>
public enum SyncFileTransportEncoding
{
    Identity = 0,
    Gzip = 1,
    ZipBundle = 2
}

/// <summary>
/// Sync queue item for store-and-forward with delta sync support.
/// Used on Edge side to queue outgoing changes.
/// </summary>
public class SyncQueue
{
    [Key]
    public long Id { get; set; }

    [Required]
    [MaxLength(50)]
    public string TableName { get; set; } = string.Empty;

    [Required]
    [MaxLength(50)]
    public string RecordKey { get; set; } = string.Empty;

    public SyncActionType ActionType { get; set; } = SyncActionType.CREATE;

    /// <summary>
    /// JSON Payload.
    /// CREATE: Full object. UPDATE: Only changed properties. DELETE: empty or key only.
    /// </summary>
    [Required]
    public string Payload { get; set; } = string.Empty;

    public SyncPriority Priority { get; set; } = SyncPriority.Low;

    public int RetryCount { get; set; } = 0;

    public int MaxRetries { get; set; } = 5;

    public DateTime? NextRetryAt { get; set; }

    [MaxLength(500)]
    public string? LastError { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime? SyncedAt { get; set; }
}

/// <summary>
/// Shore-side outbox for Shore→Edge sync.
/// Queues changes made on shore to be pulled by edge nodes.
/// </summary>
public class SyncOutbox
{
    [Key]
    public long Id { get; set; }

    /// <summary>
    /// Target edge node: "SHIP_01", "SHIP_02", or "*" for broadcast
    /// </summary>
    [Required]
    [MaxLength(50)]
    public string TargetNode { get; set; } = "*";

    [Required]
    [MaxLength(50)]
    public string TableName { get; set; } = string.Empty;

    [Required]
    [MaxLength(50)]
    public string RecordKey { get; set; } = string.Empty;

    public SyncActionType ActionType { get; set; } = SyncActionType.UPDATE;

    [Required]
    public string Payload { get; set; } = string.Empty;

    public long SyncVersion { get; set; } = 0;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime? DeliveredAt { get; set; }
}

/// <summary>
/// Audit log for all sync operations (both directions)
/// </summary>
public class SyncLog
{
    [Key]
    public long Id { get; set; }

    [Required]
    [MaxLength(20)]
    public string Direction { get; set; } = "EDGE_TO_SHORE"; // EDGE_TO_SHORE, SHORE_TO_EDGE

    [Required]
    [MaxLength(50)]
    public string OriginNode { get; set; } = string.Empty;

    [Required]
    [MaxLength(50)]
    public string TableName { get; set; } = string.Empty;

    [MaxLength(50)]
    public string RecordKey { get; set; } = string.Empty;

    [MaxLength(10)]
    public string ActionType { get; set; } = "CREATE";

    [MaxLength(20)]
    public string Status { get; set; } = "SUCCESS"; // SUCCESS, CONFLICT, FAILED

    public string? ConflictDetail { get; set; }

    public DateTime ProcessedAt { get; set; } = DateTime.UtcNow;
}

/// <summary>
/// Metadata registry for files associated with sync records.
/// Tracks whether the receiving node already has a verified local copy.
/// </summary>
public class SyncFileManifest
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [MaxLength(50)]
    public string OwnerNodeId { get; set; } = string.Empty;

    [MaxLength(50)]
    public string? ReceiverNodeId { get; set; }

    [Required]
    [MaxLength(50)]
    public string TableName { get; set; } = string.Empty;

    [Required]
    [MaxLength(50)]
    public string RecordKey { get; set; } = string.Empty;

    [Required]
    [MaxLength(50)]
    public string FileRole { get; set; } = string.Empty;

    [Required]
    [MaxLength(260)]
    public string FileName { get; set; } = string.Empty;

    [MaxLength(100)]
    public string? ContentType { get; set; }

    public long SizeBytes { get; set; }

    public long? OriginalSizeBytes { get; set; }

    [Required]
    [MaxLength(64)]
    public string Sha256 { get; set; } = string.Empty;

    [MaxLength(30)]
    public string TransportEncoding { get; set; } = nameof(SyncFileTransportEncoding.Identity).ToLowerInvariant();

    public bool IsPreprocessed { get; set; }

    [MaxLength(50)]
    public string? PreprocessProfile { get; set; }

    [MaxLength(500)]
    public string? SourcePath { get; set; }

    [MaxLength(500)]
    public string? StoragePath { get; set; }

    public SyncPriority TransferPriority { get; set; } = SyncPriority.Low;

    public SyncFileTransferStatus TransferStatus { get; set; } = SyncFileTransferStatus.MetadataOnly;

    [MaxLength(500)]
    public string? LastError { get; set; }

    public DateTime CapturedAtUtc { get; set; } = DateTime.UtcNow;

    public DateTime? LastRequestedAtUtc { get; set; }

    public DateTime? VerifiedAtUtc { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}

/// <summary>
/// Pending file request generated when metadata arrives but the receiver does not yet have the file.
/// </summary>
public class SyncFileTransferRequest
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Required]
    public Guid ManifestId { get; set; }

    public SyncFileManifest? Manifest { get; set; }

    [Required]
    [MaxLength(50)]
    public string RequesterNodeId { get; set; } = string.Empty;

    [Required]
    [MaxLength(50)]
    public string SupplierNodeId { get; set; } = string.Empty;

    public SyncFileRequestStatus Status { get; set; } = SyncFileRequestStatus.Pending;

    public int RetryCount { get; set; }

    public bool PreferDeltaTransfer { get; set; }

    public int? DeltaBlockSizeBytes { get; set; }

    [MaxLength(64)]
    public string? ReceiverBaseSha256 { get; set; }

    public string? ReceiverBlockHashesJson { get; set; }

    public DateTime RequestedAtUtc { get; set; } = DateTime.UtcNow;

    public DateTime? NextRetryAt { get; set; }

    [MaxLength(500)]
    public string? LastError { get; set; }

    public DateTime? CompletedAtUtc { get; set; }
}

/// <summary>
/// Persistent resumable chunk session used by phase 3 file transfer.
/// Tracks the next contiguous chunk expected by the receiver.
/// </summary>
public class SyncFileChunkSession
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Required]
    public Guid RequestId { get; set; }

    [Required]
    public Guid ManifestId { get; set; }

    public Guid FileId { get; set; }

    [Required]
    [MaxLength(50)]
    public string RequesterNodeId { get; set; } = string.Empty;

    [Required]
    [MaxLength(50)]
    public string SupplierNodeId { get; set; } = string.Empty;

    [Required]
    [MaxLength(20)]
    public string Direction { get; set; } = "download";

    [Required]
    [MaxLength(50)]
    public string TableName { get; set; } = string.Empty;

    [Required]
    [MaxLength(50)]
    public string RecordKey { get; set; } = string.Empty;

    [Required]
    [MaxLength(50)]
    public string FileRole { get; set; } = string.Empty;

    [Required]
    [MaxLength(260)]
    public string FileName { get; set; } = string.Empty;

    [MaxLength(100)]
    public string? ContentType { get; set; }

    public long SizeBytes { get; set; }

    [Required]
    [MaxLength(64)]
    public string Sha256 { get; set; } = string.Empty;

    public int ChunkSizeBytes { get; set; }

    public int TotalChunks { get; set; }

    public int NextChunkIndex { get; set; }

    public long CommittedBytes { get; set; }

    public bool IsDeltaSession { get; set; }

    public string? RequestedChunkIndexesJson { get; set; }

    [MaxLength(64)]
    public string? ReceiverBaseSha256 { get; set; }

    [MaxLength(500)]
    public string? SourcePath { get; set; }

    [MaxLength(500)]
    public string? StagingPath { get; set; }

    [MaxLength(500)]
    public string? StoragePath { get; set; }

    [Required]
    [MaxLength(200)]
    public string ResumeToken { get; set; } = string.Empty;

    public SyncFileChunkSessionStatus Status { get; set; } = SyncFileChunkSessionStatus.Pending;

    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;

    public DateTime LastActivityAtUtc { get; set; } = DateTime.UtcNow;

    public DateTime ExpiresAtUtc { get; set; } = DateTime.UtcNow.AddHours(12);

    public DateTime? CompletedAtUtc { get; set; }

    [MaxLength(500)]
    public string? LastError { get; set; }
}
