// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProductApi.Data;

#nullable disable

namespace productapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321120000_AddSyncNodeSecurityRegistry")]
    partial class AddSyncNodeSecurityRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new AppDbContextModelSnapshot().BuildModelForAddSyncNodeSecurityRegistry(modelBuilder);
        }
    }
}