using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace productapi.Migrations
{
    /// <inheritdoc />
    public partial class AddReportEvaluations : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Fully idempotent: uses IF NOT EXISTS for all DDL to handle
            // databases where these objects were created outside of EF migrations.
            migrationBuilder.Sql(@"
                -- sync_node_trackers columns
                ALTER TABLE sync_node_trackers ADD COLUMN IF NOT EXISTS ""IsRegistered"" boolean NOT NULL DEFAULT FALSE;
                ALTER TABLE sync_node_trackers ADD COLUMN IF NOT EXISTS ""IsRevoked"" boolean NOT NULL DEFAULT FALSE;
                ALTER TABLE sync_node_trackers ADD COLUMN IF NOT EXISTS ""KeyVersion"" integer NOT NULL DEFAULT 0;
                ALTER TABLE sync_node_trackers ADD COLUMN IF NOT EXISTS ""LastAcknowledgedKeyVersion"" integer NULL;
                ALTER TABLE sync_node_trackers ADD COLUMN IF NOT EXISTS ""LastKeyRotatedAt"" timestamp with time zone NULL;
                ALTER TABLE sync_node_trackers ADD COLUMN IF NOT EXISTS ""LastKeyVersionAcknowledgedAt"" timestamp with time zone NULL;
                ALTER TABLE sync_node_trackers ADD COLUMN IF NOT EXISTS ""LastSignedRequestAt"" timestamp with time zone NULL;
                ALTER TABLE sync_node_trackers ADD COLUMN IF NOT EXISTS ""PreviousKeyGraceUntil"" timestamp with time zone NULL;
                ALTER TABLE sync_node_trackers ADD COLUMN IF NOT EXISTS ""PreviousKeyVersion"" integer NULL;
                ALTER TABLE sync_node_trackers ADD COLUMN IF NOT EXISTS ""PreviousSigningKey"" character varying(500) NULL;
                ALTER TABLE sync_node_trackers ADD COLUMN IF NOT EXISTS ""RevokedAt"" timestamp with time zone NULL;
                ALTER TABLE sync_node_trackers ADD COLUMN IF NOT EXISTS ""RevokedReason"" character varying(500) NULL;
                ALTER TABLE sync_node_trackers ADD COLUMN IF NOT EXISTS ""SigningKey"" character varying(500) NULL;

                -- ReportEvaluations
                CREATE TABLE IF NOT EXISTS ""ReportEvaluations"" (
                    ""Id"" uuid NOT NULL,
                    ""ReportId"" uuid NOT NULL,
                    ""Status"" character varying(20) NOT NULL,
                    ""ContentVi"" text NOT NULL,
                    ""CreatedDate"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_ReportEvaluations"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_ReportEvaluations_noon_reports_ReportId""
                        FOREIGN KEY (""ReportId"") REFERENCES noon_reports (""Id"") ON DELETE CASCADE
                );

                -- sync_dlq_items
                CREATE TABLE IF NOT EXISTS sync_dlq_items (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""BatchId"" character varying(255) NOT NULL,
                    ""ItemId"" character varying(255) NOT NULL,
                    ""Priority"" integer NOT NULL,
                    ""ItemContent"" bytea NOT NULL,
                    ""ErrorReason"" character varying(1000),
                    ""FailureCount"" integer NOT NULL,
                    ""LastFailedAtUtc"" timestamp with time zone,
                    ""MovedToDlqAtUtc"" timestamp with time zone NOT NULL,
                    ""OriginEdgeNode"" character varying(50),
                    ""DiagnosticInfo"" character varying(500),
                    ""IsApprovedForManualReplay"" boolean NOT NULL,
                    ""ManualReviewNotes"" character varying(500),
                    CONSTRAINT ""PK_sync_dlq_items"" PRIMARY KEY (""Id"")
                );

                -- sync_file_manifests (must exist before sync_file_transfer_requests)
                CREATE TABLE IF NOT EXISTS sync_file_manifests (
                    ""Id"" uuid NOT NULL,
                    ""OwnerNodeId"" character varying(50) NOT NULL,
                    ""ReceiverNodeId"" character varying(50),
                    ""TableName"" character varying(50) NOT NULL,
                    ""RecordKey"" character varying(50) NOT NULL,
                    ""FileRole"" character varying(50) NOT NULL,
                    ""FileName"" character varying(260) NOT NULL,
                    ""ContentType"" character varying(100),
                    ""SizeBytes"" bigint NOT NULL,
                    ""OriginalSizeBytes"" bigint,
                    ""Sha256"" character varying(64) NOT NULL,
                    ""TransportEncoding"" character varying(30) NOT NULL,
                    ""IsPreprocessed"" boolean NOT NULL,
                    ""PreprocessProfile"" character varying(50),
                    ""SourcePath"" character varying(500),
                    ""StoragePath"" character varying(500),
                    ""TransferPriority"" integer NOT NULL,
                    ""TransferStatus"" integer NOT NULL,
                    ""LastError"" character varying(500),
                    ""CapturedAtUtc"" timestamp with time zone NOT NULL,
                    ""LastRequestedAtUtc"" timestamp with time zone,
                    ""VerifiedAtUtc"" timestamp with time zone,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NOT NULL,
                    CONSTRAINT ""PK_sync_file_manifests"" PRIMARY KEY (""Id"")
                );

                -- sync_file_chunk_sessions
                CREATE TABLE IF NOT EXISTS sync_file_chunk_sessions (
                    ""Id"" uuid NOT NULL,
                    ""RequestId"" uuid NOT NULL,
                    ""ManifestId"" uuid NOT NULL,
                    ""FileId"" uuid NOT NULL,
                    ""RequesterNodeId"" character varying(50) NOT NULL,
                    ""SupplierNodeId"" character varying(50) NOT NULL,
                    ""Direction"" character varying(20) NOT NULL,
                    ""TableName"" character varying(50) NOT NULL,
                    ""RecordKey"" character varying(50) NOT NULL,
                    ""FileRole"" character varying(50) NOT NULL,
                    ""FileName"" character varying(260) NOT NULL,
                    ""ContentType"" character varying(100),
                    ""SizeBytes"" bigint NOT NULL,
                    ""Sha256"" character varying(64) NOT NULL,
                    ""ChunkSizeBytes"" integer NOT NULL,
                    ""TotalChunks"" integer NOT NULL,
                    ""NextChunkIndex"" integer NOT NULL,
                    ""CommittedBytes"" bigint NOT NULL,
                    ""IsDeltaSession"" boolean NOT NULL,
                    ""RequestedChunkIndexesJson"" text,
                    ""ReceiverBaseSha256"" character varying(64),
                    ""SourcePath"" character varying(500),
                    ""StagingPath"" character varying(500),
                    ""StoragePath"" character varying(500),
                    ""ResumeToken"" character varying(200) NOT NULL,
                    ""Status"" integer NOT NULL,
                    ""CreatedAtUtc"" timestamp with time zone NOT NULL,
                    ""LastActivityAtUtc"" timestamp with time zone NOT NULL,
                    ""ExpiresAtUtc"" timestamp with time zone NOT NULL,
                    ""CompletedAtUtc"" timestamp with time zone,
                    ""LastError"" character varying(500),
                    CONSTRAINT ""PK_sync_file_chunk_sessions"" PRIMARY KEY (""Id"")
                );

                -- sync_nonce_registry
                CREATE TABLE IF NOT EXISTS sync_nonce_registry (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                    ""Nonce"" character varying(255) NOT NULL,
                    ""OriginNode"" character varying(50) NOT NULL,
                    ""OriginTimestampUtc"" timestamp with time zone NOT NULL,
                    ""RegisteredAtUtc"" timestamp with time zone NOT NULL,
                    ""ExpiresAtUtc"" timestamp with time zone NOT NULL,
                    ""RequesterIpAddress"" character varying(45),
                    ""EndpointPath"" character varying(255),
                    CONSTRAINT ""PK_sync_nonce_registry"" PRIMARY KEY (""Id"")
                );

                -- sync_file_transfer_requests
                CREATE TABLE IF NOT EXISTS sync_file_transfer_requests (
                    ""Id"" uuid NOT NULL,
                    ""ManifestId"" uuid NOT NULL,
                    ""RequesterNodeId"" character varying(50) NOT NULL,
                    ""SupplierNodeId"" character varying(50) NOT NULL,
                    ""Status"" integer NOT NULL,
                    ""RetryCount"" integer NOT NULL,
                    ""PreferDeltaTransfer"" boolean NOT NULL,
                    ""DeltaBlockSizeBytes"" integer,
                    ""ReceiverBaseSha256"" character varying(64),
                    ""ReceiverBlockHashesJson"" text,
                    ""RequestedAtUtc"" timestamp with time zone NOT NULL,
                    ""NextRetryAt"" timestamp with time zone,
                    ""LastError"" character varying(500),
                    ""CompletedAtUtc"" timestamp with time zone,
                    CONSTRAINT ""PK_sync_file_transfer_requests"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_sync_file_transfer_requests_sync_file_manifests_ManifestId""
                        FOREIGN KEY (""ManifestId"") REFERENCES sync_file_manifests (""Id"") ON DELETE CASCADE
                );

                -- Indexes
                CREATE INDEX IF NOT EXISTS ""IX_sync_node_trackers_IsRegistered"" ON sync_node_trackers (""IsRegistered"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_node_trackers_IsRevoked"" ON sync_node_trackers (""IsRevoked"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_ReportEvaluations_ReportId"" ON ""ReportEvaluations"" (""ReportId"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_dlq_items_IsApprovedForManualReplay_MovedToDlqAtUtc"" ON sync_dlq_items (""IsApprovedForManualReplay"", ""MovedToDlqAtUtc"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_dlq_items_MovedToDlqAtUtc"" ON sync_dlq_items (""MovedToDlqAtUtc"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_dlq_items_OriginEdgeNode"" ON sync_dlq_items (""OriginEdgeNode"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_dlq_items_Priority"" ON sync_dlq_items (""Priority"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_file_chunk_sessions_ExpiresAtUtc"" ON sync_file_chunk_sessions (""ExpiresAtUtc"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_file_chunk_sessions_ManifestId_Direction_Status"" ON sync_file_chunk_sessions (""ManifestId"", ""Direction"", ""Status"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_file_chunk_sessions_RequesterNodeId_SupplierNodeId_Dir~"" ON sync_file_chunk_sessions (""RequesterNodeId"", ""SupplierNodeId"", ""Direction"", ""Status"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_sync_file_chunk_sessions_ResumeToken"" ON sync_file_chunk_sessions (""ResumeToken"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_file_manifests_OwnerNodeId_TableName_RecordKey"" ON sync_file_manifests (""OwnerNodeId"", ""TableName"", ""RecordKey"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_file_manifests_ReceiverNodeId_TransferStatus"" ON sync_file_manifests (""ReceiverNodeId"", ""TransferStatus"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_file_manifests_Sha256"" ON sync_file_manifests (""Sha256"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_file_transfer_requests_ManifestId"" ON sync_file_transfer_requests (""ManifestId"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_file_transfer_requests_RequesterNodeId_Status"" ON sync_file_transfer_requests (""RequesterNodeId"", ""Status"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_file_transfer_requests_SupplierNodeId_Status"" ON sync_file_transfer_requests (""SupplierNodeId"", ""Status"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_nonce_registry_ExpiresAtUtc"" ON sync_nonce_registry (""ExpiresAtUtc"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_sync_nonce_registry_Nonce"" ON sync_nonce_registry (""Nonce"");
                CREATE INDEX IF NOT EXISTS ""IX_sync_nonce_registry_OriginNode_RegisteredAtUtc"" ON sync_nonce_registry (""OriginNode"", ""RegisteredAtUtc"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ReportEvaluations");

            migrationBuilder.DropTable(
                name: "sync_dlq_items");

            migrationBuilder.DropTable(
                name: "sync_file_chunk_sessions");

            migrationBuilder.DropTable(
                name: "sync_file_transfer_requests");

            migrationBuilder.DropTable(
                name: "sync_nonce_registry");

            migrationBuilder.DropTable(
                name: "sync_file_manifests");

            migrationBuilder.DropIndex(
                name: "IX_sync_node_trackers_IsRegistered",
                table: "sync_node_trackers");

            migrationBuilder.DropIndex(
                name: "IX_sync_node_trackers_IsRevoked",
                table: "sync_node_trackers");

            migrationBuilder.DropColumn(
                name: "IsRegistered",
                table: "sync_node_trackers");

            migrationBuilder.DropColumn(
                name: "IsRevoked",
                table: "sync_node_trackers");

            migrationBuilder.DropColumn(
                name: "KeyVersion",
                table: "sync_node_trackers");

            migrationBuilder.DropColumn(
                name: "LastAcknowledgedKeyVersion",
                table: "sync_node_trackers");

            migrationBuilder.DropColumn(
                name: "LastKeyRotatedAt",
                table: "sync_node_trackers");

            migrationBuilder.DropColumn(
                name: "LastKeyVersionAcknowledgedAt",
                table: "sync_node_trackers");

            migrationBuilder.DropColumn(
                name: "LastSignedRequestAt",
                table: "sync_node_trackers");

            migrationBuilder.DropColumn(
                name: "PreviousKeyGraceUntil",
                table: "sync_node_trackers");

            migrationBuilder.DropColumn(
                name: "PreviousKeyVersion",
                table: "sync_node_trackers");

            migrationBuilder.DropColumn(
                name: "PreviousSigningKey",
                table: "sync_node_trackers");

            migrationBuilder.DropColumn(
                name: "RevokedAt",
                table: "sync_node_trackers");

            migrationBuilder.DropColumn(
                name: "RevokedReason",
                table: "sync_node_trackers");

            migrationBuilder.DropColumn(
                name: "SigningKey",
                table: "sync_node_trackers");
        }
    }
}
