// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace productapi.Migrations
{
    partial class AppDbContextModelSnapshot
    {
        internal void BuildLatestModelForMigration(ModelBuilder modelBuilder)
        {
            BuildModel(modelBuilder);
        }

        internal void BuildModelForAddSyncNodeSecurityRegistry(ModelBuilder modelBuilder)
        {
            BuildModel(modelBuilder);

            var syncNodeTracker = modelBuilder.Model.FindEntityType("ProductApi.Models.SyncNodeTracker");
            if (syncNodeTracker == null)
            {
                return;
            }

            RemoveProperty(syncNodeTracker, "LastAcknowledgedKeyVersion");
            RemoveProperty(syncNodeTracker, "LastKeyVersionAcknowledgedAt");
            RemoveProperty(syncNodeTracker, "PreviousSigningKey");
            RemoveProperty(syncNodeTracker, "PreviousKeyVersion");
            RemoveProperty(syncNodeTracker, "PreviousKeyGraceUntil");
        }

        private static void RemoveProperty(IMutableEntityType entityType, string propertyName)
        {
            var property = entityType.FindProperty(propertyName);
            if (property != null)
            {
                entityType.RemoveProperty(property);
            }
        }
    }
}