param(
    [string]$SourceMigrationsPath = "../edge-services/Data/Migrations",
    [string]$DumpPath = "../production/init-scripts/00-edge-dump.sql",
    [string]$OutputSqlPath = "../artifacts/tmp-build/edge-migration-baseline-fix.sql",
    [string]$ProductVersion = "8.0.0"
)

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$sourcePath = Resolve-Path (Join-Path $scriptDir $SourceMigrationsPath)
$dumpPath = Resolve-Path (Join-Path $scriptDir $DumpPath)
$outputPath = Join-Path $scriptDir $OutputSqlPath
$outputDir = Split-Path -Parent $outputPath

if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

Write-Host "Source migrations path: $sourcePath"
Write-Host "Dump path: $dumpPath"
Write-Host "Output SQL path: $outputPath"

# Source-of-truth migration IDs from code files (exclude .Designer.cs + snapshot).
$sourceIds = Get-ChildItem -Path $sourcePath -File -Filter "*.cs" |
    Where-Object { $_.Name -match "^\d{14}_.+\.cs$" -and $_.Name -notmatch "\.Designer\.cs$" } |
    ForEach-Object { [System.IO.Path]::GetFileNameWithoutExtension($_.Name) } |
    Sort-Object -Unique

if (-not $sourceIds -or $sourceIds.Count -eq 0) {
    throw "No migration IDs found in source path: $sourcePath"
}

# Parse migration IDs from dump's __EFMigrationsHistory COPY rows.
$dumpLines = Get-Content -Path $dumpPath
$dumpIds = $dumpLines |
    ForEach-Object {
        if ($_ -match "^(\d{14}_[A-Za-z0-9_]+)\s+\d+\.\d+\.\d+") {
            $matches[1]
        }
    } |
    Where-Object { $_ } |
    Sort-Object -Unique

if (-not $dumpIds -or $dumpIds.Count -eq 0) {
    throw "No migration IDs parsed from dump history in: $dumpPath"
}

$missingInDump = Compare-Object -ReferenceObject $sourceIds -DifferenceObject $dumpIds -PassThru |
    Where-Object { $_ -in $sourceIds } |
    Sort-Object

$extraInDump = Compare-Object -ReferenceObject $sourceIds -DifferenceObject $dumpIds -PassThru |
    Where-Object { $_ -in $dumpIds } |
    Sort-Object

Write-Host ""
Write-Host "=== Baseline Summary ==="
Write-Host ("Source migrations: {0}" -f $sourceIds.Count)
Write-Host ("Dump history rows: {0}" -f $dumpIds.Count)
Write-Host ("Missing in dump: {0}" -f $missingInDump.Count)
Write-Host ("Extra in dump: {0}" -f $extraInDump.Count)

if ($missingInDump.Count -gt 0) {
    Write-Host ""
    Write-Host "Migrations present in source but missing from dump history:"
    $missingInDump | ForEach-Object { Write-Host " - $_" }
} else {
    Write-Host ""
    Write-Host "No missing migration IDs in dump history."
}

if ($extraInDump.Count -gt 0) {
    Write-Host ""
    Write-Host "Migrations present in dump history but missing from source:"
    $extraInDump | ForEach-Object { Write-Host " - $_" }
}

# Generate idempotent SQL to stamp only missing source migrations.
$sql = New-Object System.Collections.Generic.List[string]
$sql.Add("-- Auto-generated by scripts/check-ef-baseline.ps1")
$sql.Add("-- Purpose: align __EFMigrationsHistory with source migrations without rerunning DDL")
$sql.Add("BEGIN;")

if ($missingInDump.Count -eq 0) {
    $sql.Add("-- No missing migration IDs detected.")
} else {
    foreach ($id in $missingInDump) {
        $sql.Add('INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")')
        $sql.Add(('SELECT ''{0}'', ''{1}''' -f $id, $ProductVersion))
        $sql.Add("WHERE NOT EXISTS (")
        $sql.Add(('  SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = ''{0}''' -f $id))
        $sql.Add(");")
    }
}

$sql.Add("COMMIT;")

Set-Content -Path $outputPath -Value $sql -Encoding UTF8
Write-Host ""
Write-Host "Generated: $outputPath"

if ($missingInDump.Count -gt 0) {
    Write-Host "Review and apply this SQL on edge DB before enabling EDGE_DATABASE_AUTO_MIGRATE=true."
}
