param(
    [string]$BaselineName = "BaselineSchema",
    [string]$ProjectPath = "../edge-services/EdgeCollector.csproj",
    [string]$MigrationsPath = "../edge-services/Data/Migrations",
    [string]$OutputStampSqlPath = "../artifacts/tmp-build/edge-baseline-history-stamp.sql",
    [string]$ArchiveRoot = "../artifacts/tmp-build/migrations-archive",
    [string]$ProductVersion = "8.0.0",
    [switch]$Execute
)

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$resolvedProjectPath = Resolve-Path (Join-Path $scriptDir $ProjectPath)
$resolvedMigrationsPath = Resolve-Path (Join-Path $scriptDir $MigrationsPath)
$resolvedArchiveRoot = Join-Path $scriptDir $ArchiveRoot
$resolvedStampSqlPath = Join-Path $scriptDir $OutputStampSqlPath

if (-not (Test-Path (Split-Path -Parent $resolvedStampSqlPath))) {
    New-Item -ItemType Directory -Path (Split-Path -Parent $resolvedStampSqlPath) -Force | Out-Null
}
if (-not (Test-Path $resolvedArchiveRoot)) {
    New-Item -ItemType Directory -Path $resolvedArchiveRoot -Force | Out-Null
}

$dotnetCmd = Get-Command dotnet -ErrorAction SilentlyContinue
if (-not $dotnetCmd) {
    throw "dotnet CLI was not found in PATH."
}

$efToolCheck = & dotnet ef --version 2>$null
if ($LASTEXITCODE -ne 0) {
    throw "dotnet-ef tool is not available. Install with: dotnet tool install --global dotnet-ef"
}

$existingMigrationFiles = Get-ChildItem -Path $resolvedMigrationsPath -File -Filter "*.cs"
$timestamp = Get-Date -Format "yyyyMMddHHmmss"
$archiveDir = Join-Path $resolvedArchiveRoot $timestamp

Write-Host "Project: $resolvedProjectPath"
Write-Host "Migrations: $resolvedMigrationsPath"
Write-Host "Existing migration .cs files: $($existingMigrationFiles.Count)"
Write-Host "Planned baseline name: $BaselineName"
Write-Host "Planned archive dir: $archiveDir"
Write-Host ""

if (-not $Execute) {
    Write-Host "Preview mode (safe): no files changed."
    Write-Host "Re-run with -Execute to apply changes."
    Write-Host ""
    Write-Host "Planned commands:"
    Write-Host "1) Move current migration files to archive"
    Write-Host "2) dotnet ef migrations add $BaselineName --project $resolvedProjectPath --startup-project $resolvedProjectPath --context EdgeDbContext --output-dir Data/Migrations"
    Write-Host "3) Generate history-stamp SQL at: $resolvedStampSqlPath"
    exit 0
}

New-Item -ItemType Directory -Path $archiveDir -Force | Out-Null

foreach ($file in $existingMigrationFiles) {
    Move-Item -Path $file.FullName -Destination (Join-Path $archiveDir $file.Name) -Force
}

Write-Host "Archived old migration files to: $archiveDir"

& dotnet ef migrations add $BaselineName --project $resolvedProjectPath --startup-project $resolvedProjectPath --context EdgeDbContext --output-dir Data/Migrations
if ($LASTEXITCODE -ne 0) {
    throw "Failed to create baseline migration."
}

$generatedMigration = Get-ChildItem -Path $resolvedMigrationsPath -File -Filter "*_*.cs" |
    Where-Object { $_.Name -match "^\d{14}_${BaselineName}\.cs$" } |
    Sort-Object LastWriteTime -Descending |
    Select-Object -First 1

if (-not $generatedMigration) {
    throw "Could not locate generated migration file for baseline name '$BaselineName'."
}

$generatedMigrationId = [System.IO.Path]::GetFileNameWithoutExtension($generatedMigration.Name)

$sql = @(
    "-- Generated by scripts/rebaseline-edge-migrations.ps1",
    "-- Apply on existing DB to mark baseline as already applied.",
    "BEGIN;",
    'INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")',
    "SELECT '$generatedMigrationId', '$ProductVersion'",
    "WHERE NOT EXISTS (",
    ('  SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = ''{0}''' -f $generatedMigrationId),
    ");",
    "COMMIT;"
)

Set-Content -Path $resolvedStampSqlPath -Value $sql -Encoding UTF8

Write-Host ""
Write-Host "Rebaseline completed."
Write-Host "Generated migration id: $generatedMigrationId"
Write-Host "History stamp SQL: $resolvedStampSqlPath"
Write-Host "IMPORTANT: Do not run 'dotnet ef database update' against populated production DB."
