using System;
using System.Collections.Generic;

namespace MaritimeEdge.DTOs.Drill
{
    /// <summary>
    /// DTO for DrillType master data
    /// Used for dropdown lists and drill type selection
    /// </summary>
    public class DrillTypeDto
    {
        public Guid Id { get; set; }
        public string DrillCode { get; set; } = string.Empty;
        public string DrillName { get; set; } = string.Empty;
        public string? DrillNameLocal { get; set; }
        public string Category { get; set; } = string.Empty;
        public string? RegulationSource { get; set; }
        public string? RegulationPeriod { get; set; }
        public string FrequencyType { get; set; } = string.Empty;
        public int? FrequencyDays { get; set; }
        public string? TriggerCondition { get; set; }
        public int? TriggerWithinDays { get; set; }
        public int WarningDaysBefore { get; set; }
        public string? AssignedToRole { get; set; }
        public string? InstructionContent { get; set; }
        
        // Checkboxes from Ảnh 3
        public bool IsFixedInterval { get; set; }
        public bool IsDocumentRequired { get; set; }
        public bool IsSecureHistory { get; set; }
        public bool IsCrewMemberRequired { get; set; }
        public bool IsMandatorySignOnEvaluation { get; set; }
        public bool HasNoExpiry { get; set; }
        
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
    }

    /// <summary>
    /// DTO for Drill Schedule timeline view (Ảnh 2)
    /// Represents horizontal bars in Gantt chart
    /// </summary>
    public class DrillScheduleDto
    {
        public Guid Id { get; set; }
        public string ScheduleCode { get; set; } = string.Empty;
        
        // Drill Type info
        public Guid DrillTypeId { get; set; }
        public string DrillCode { get; set; } = string.Empty;
        public string DrillName { get; set; } = string.Empty;
        public string? DrillNameLocal { get; set; }
        public string Category { get; set; } = string.Empty;
        
        // Schedule timing (from Ảnh 3 form fields)
        public int ScheduledMonth { get; set; }
        public int ScheduledYear { get; set; }
        public DateTime StartDate { get; set; } // "Start date" field
        public DateTime DueDate { get; set; } // "Due date" field
        public DateTime OverdueDate { get; set; }
        
        // Status for color mapping in Ảnh 2
        // RED: OVERDUE, GREEN: COMPLETED, YELLOW: DUE, BLUE: SCHEDULED
        public string Status { get; set; } = string.Empty;
        
        // Timeline label (e.g., "2 w", "3 m", "-2 d", "6 d" from Ảnh 2)
        public string? TimelineLabel { get; set; }
        
        // Assignment
        public Guid? AssignedToCrewId { get; set; }
        public string? AssignedToCrewName { get; set; }
        public string? AssignedToRole { get; set; }
        
        // Execution tracking
        public DateTime? LastExecutedDate { get; set; }
        public int ExecutionCount { get; set; }
        public bool IsAutoGenerated { get; set; }
        
        // Rich text content and remarks from edit modal
        public string? Remarks { get; set; }
        public string? InstructionContent { get; set; }
        
        // Options checkboxes from Ảnh 3 modal
        public bool IsFixedInterval { get; set; }
        public bool IsDocumentRequired { get; set; }
        public bool IsSecureHistory { get; set; }
        public bool IsCrewMemberRequired { get; set; }
        public bool IsMandatorySignOnEvaluation { get; set; }
        
        // Participants - list of crew member IDs (only when IsCrewMemberRequired = true)
        public List<Guid>? Participants { get; set; }
        
        // Sync fields
        public string OriginNode { get; set; } = string.Empty;
        public bool IsSynced { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }

    /// <summary>
    /// DTO for creating/updating drill schedule
    /// Maps to fields in Ảnh 3 modal
    /// </summary>
    public class CreateUpdateDrillScheduleDto
    {
        public Guid DrillTypeId { get; set; }
        
        // From "Drill details" section in Ảnh 3
        public string? Description { get; set; } // Same as DrillName, editable
        public string? Category { get; set; }
        
        // Type: Interval or One-time (radio buttons in Ảnh 3)
        public bool IsInterval { get; set; } = true;
        
        // Interval fields (only if IsInterval = true)
        public int? IntervalValue { get; set; } // e.g., 1
        public string? IntervalUnit { get; set; } // "months", "weeks", "days"
        
        // Date fields from Ảnh 3
        public DateTime StartDate { get; set; }
        public DateTime DueDate { get; set; }
        public int BeforeDueDays { get; set; } = 7; // "Before due" field
        public bool HasNoExpiry { get; set; } = false;
        
        // Assignment
        public Guid? AssignedToCrewId { get; set; }
        public string? AssignedToRole { get; set; }
        
        // Checkboxes from Ảnh 3
        public bool IsFixedInterval { get; set; } = true;
        public bool IsDocumentRequired { get; set; } = false;
        public bool IsSecureHistory { get; set; } = false;
        public bool IsCrewMemberRequired { get; set; } = false;
        public bool IsMandatorySignOnEvaluation { get; set; } = false;
        
        // Rich text content from "Data card" tab
        public string? InstructionContent { get; set; }
        
        public string? Remarks { get; set; }
        
        // Participants - list of crew member IDs (only when IsCrewMemberRequired = true)
        public List<Guid>? Participants { get; set; }
    }

    /// <summary>
    /// DTO for Drill Log (execution record)
    /// Created when user completes a drill and clicks "Save"
    /// </summary>
    public class DrillLogDto
    {
        public Guid Id { get; set; }
        public string LogCode { get; set; } = string.Empty;
        
        public Guid? DrillScheduleId { get; set; }
        public string? ScheduleCode { get; set; }
        public Guid DrillTypeId { get; set; }
        public string DrillCode { get; set; } = string.Empty;
        public string DrillName { get; set; } = string.Empty;
        
        // Execution info
        public DateTime ExecutionDate { get; set; }
        public TimeSpan? ExecutionTime { get; set; }
        public TimeSpan? Duration { get; set; }
        public string? Location { get; set; }
        public string? WeatherCondition { get; set; }
        
        // Results
        public string Result { get; set; } = string.Empty; // PASS, FAIL, PARTIAL
        public string? OverallAssessment { get; set; }
        
        // Participants
        public List<DrillParticipantDto>? Participants { get; set; }
        public int TotalParticipants { get; set; }
        public int NewCrewCount { get; set; }
        
        // Observations
        public string? Findings { get; set; }
        public string? CorrectiveActions { get; set; }
        public string? GeneralRemarks { get; set; }
        public string? LessonsLearned { get; set; }
        
        // Approval (from Ảnh 3: "EVERY DRILL REPORT NEEDS TO BE APPROVED BY THE MASTER")
        public Guid? ConductedByCrewId { get; set; }
        public string? ConductedByCrewName { get; set; }
        public Guid? VerifiedByCrewId { get; set; }
        public string? VerifiedByCrewName { get; set; }
        public DateTime? VerifiedDate { get; set; }
        public bool IsLocked { get; set; }
        
        // Attachments
        public List<string>? AttachmentUrls { get; set; }
        
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }

    /// <summary>
    /// DTO for drill participant (stored as JSON in DrillLog)
    /// </summary>
    public class DrillParticipantDto
    {
        public Guid CrewId { get; set; }
        public string CrewName { get; set; } = string.Empty;
        public string? Rank { get; set; }
        public string? Role { get; set; } // "Team Leader", "Participant", "Observer"
        public bool IsNewCrew { get; set; } // For tracking *1 rule (25% turnover)
        public string? Performance { get; set; } // "Excellent", "Good", "Satisfactory", etc.
    }

    /// <summary>
    /// Request DTO for creating drill log
    /// </summary>
    public class CreateDrillLogDto
    {
        public Guid? DrillScheduleId { get; set; }
        public Guid DrillTypeId { get; set; }
        
        public DateTime ExecutionDate { get; set; }
        public TimeSpan? ExecutionTime { get; set; }
        public TimeSpan? Duration { get; set; }
        public string? Location { get; set; }
        public string? WeatherCondition { get; set; }
        
        public string Result { get; set; } = "PASS";
        public string? OverallAssessment { get; set; }
        
        public List<DrillParticipantDto> Participants { get; set; } = new();
        
        public string? Findings { get; set; }
        public string? CorrectiveActions { get; set; }
        public string? GeneralRemarks { get; set; }
        public string? LessonsLearned { get; set; }
        
        public Guid ConductedByCrewId { get; set; }
        
        public List<string>? AttachmentUrls { get; set; }
    }

    /// <summary>
    /// Request DTO for Master approval
    /// </summary>
    public class ApproveDrillLogDto
    {
        public Guid VerifiedByCrewId { get; set; }
        public string? ApprovalRemarks { get; set; }
    }

    /// <summary>
    /// Statistics DTO for dashboard/summary view
    /// </summary>
    public class DrillStatisticsDto
    {
        public int TotalScheduled { get; set; }
        public int TotalCompleted { get; set; }
        public int TotalOverdue { get; set; }
        public int TotalUpcoming { get; set; }
        
        public Dictionary<string, int> ByCategory { get; set; } = new();
        public Dictionary<string, int> ByStatus { get; set; } = new();
        
        public List<DrillScheduleDto> UpcomingDrills { get; set; } = new();
        public List<DrillScheduleDto> OverdueDrills { get; set; } = new();
        
        public double ComplianceRate { get; set; } // Percentage of completed vs scheduled
    }

    /// <summary>
    /// Query parameters for timeline view filtering (Ảnh 2)
    /// </summary>
    public class DrillTimelineQueryDto
    {
        public int? Year { get; set; }
        public int? Month { get; set; }
        public string? Category { get; set; } // Filter by STATION_DRILLS, EXERCISES, etc.
        public string? Status { get; set; } // Filter by SCHEDULED, OVERDUE, COMPLETED
        public Guid? AssignedToCrewId { get; set; }
        public bool? ShowOverdueOnly { get; set; }
        
        // Date range for timeline display
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
    }

    /// <summary>
    /// Response for grouped timeline data (for tree view in Ảnh 2)
    /// </summary>
    public class DrillTimelineGroupDto
    {
        public string Category { get; set; } = string.Empty;
        public string CategoryDisplayName { get; set; } = string.Empty; // Human-readable: "Station Drills"
        public int TotalDrills { get; set; }
        public int CompletedCount { get; set; }
        public int OverdueCount { get; set; }
        public bool IsExpanded { get; set; } = true;
        
        public List<DrillScheduleDto> Schedules { get; set; } = new();
    }

    /// <summary>
    /// Request for bulk delete operation
    /// </summary>
    public class BulkDeleteRequest
    {
        public List<Guid> ScheduleIds { get; set; } = new();
        public string? Reason { get; set; }
    }
}
