/**
 * Drill Training Management Types
 * SOLAS/ISPS Compliance - ISM Code 10
 */

// ============================================================
// ENUMS & STATUS TYPES
// ============================================================

export type DrillCategory = 
  | 'STATION_DRILLS'
  | 'EXERCISES'
  | 'EDUCATION'
  | 'TRAINING'
  | 'CHECKS'
  | 'ISPS';

export type DrillFrequencyType = 
  | 'MONTHLY'
  | 'BI_MONTHLY'
  | 'QUARTERLY'
  | 'SEMI_ANNUAL'
  | 'ANNUAL'
  | 'FIVE_YEARS'
  | 'ON_EVENT';

export type DrillTriggerCondition = 
  | 'ROUTINE'
  | 'ON_DEPARTURE'
  | 'ON_NEW_CREW'
  | 'ON_BALLAST';

export type DrillScheduleStatus = 
  | 'SCHEDULED'
  | 'DUE'
  | 'OVERDUE'
  | 'COMPLETED'
  | 'CANCELLED';

export type DrillResult = 
  | 'PASS'
  | 'FAIL'
  | 'PARTIAL';

// ============================================================
// DRILL TYPE (Master Data from Excel Ảnh 1)
// ============================================================

export interface DrillType {
  id: string;
  drillCode: string; // e.g., "ABANDON_SHIP_MONTHLY"
  drillName: string; // e.g., "Abandon ship drill (SOLAS III 19.3.2 & 19.3.4)"
  drillNameLocal?: string; // Vietnamese name
  category: DrillCategory;
  regulationSource: string; // e.g., "SOLAS III 19.3.2 & 19.3.4"
  regulationPeriod?: string; // e.g., "Monthly" or "Quarterly"
  frequencyType: DrillFrequencyType;
  frequencyDays: number; // 30, 60, 90, 180, 365, 1825, etc.
  triggerCondition?: DrillTriggerCondition;
  triggerWithinDays?: number; // 1 (24h), 7 (1 week), 14 (2 weeks), etc.
  warningDaysBefore: number; // Default 7 days
  assignedToRole?: string; // "MASTER", "CHIEF_OFFICER", "CHIEF_ENGINEER", etc.
  displayOrder: number;
  
  // Instruction content (HTML for "Data card" tab in Ảnh 3)
  instructionContent?: string;
  
  // Checkboxes from Ảnh 3 Edit Modal
  isFixedInterval: boolean; // "Fixed intervals" checkbox
  isDocumentRequired: boolean; // "Document is required" checkbox
  isSecureHistory: boolean; // "Secure history" checkbox
  isCrewMemberRequired: boolean; // "Crew Member Required" checkbox
  isMandatorySignOnEvaluation: boolean; // "Mandatory sign on evaluation" checkbox
  hasNoExpiry: boolean; // "No expiry" checkbox
  
  isActive: boolean;
  originNode?: string; // "EDGE" or "SHORE"
  isSynced: boolean;
  createdAt: string;
  updatedAt?: string;
}

// ============================================================
// DRILL SCHEDULE (Timeline Bar from Ảnh 2)
// ============================================================

export interface DrillSchedule {
  id: string;
  scheduleCode: string; // e.g., "DS-202501-FIRE_DRILL-abc12345"
  drillTypeId: string;
  drillType?: DrillType; // Populated from API with drill details
  drillName?: string; // Denormalized for quick access
  category?: DrillCategory;
  
  scheduledMonth: number; // 1-12
  scheduledYear: number;
  startDate: string; // ISO date
  dueDate: string; // ISO date
  overdueDate?: string; // ISO date
  
  status: DrillScheduleStatus;
  timelineLabel: string; // "2 w", "3 m", "-2 d", "6 d" (calculated from CalculateTimelineLabel)
  
  assignedToCrewId?: string;
  assignedToCrewName?: string; // CrewMember.FullName
  
  executionCount: number; // How many times this drill was executed
  isAutoGenerated: boolean; // True for auto-scheduler, False for manual entry
  
  remarks?: string;
  instructionContent?: string; // Rich text content from Data card tab
  
  // Options checkboxes from Ảnh 3 modal
  isFixedInterval?: boolean;
  isDocumentRequired?: boolean;
  isSecureHistory?: boolean;
  isCrewMemberRequired?: boolean;
  isMandatorySignOnEvaluation?: boolean;
  
  // Participants - array of crew member IDs (when isCrewMemberRequired = true)
  participants?: string[];
  
  // Documents/Attachments
  documents?: DocumentAttachment[];
  
  vesselId?: string;
  originNode?: string; // "EDGE" or "SHORE"
  isSynced: boolean;
  createdAt: string;
  updatedAt?: string;
}

// ============================================================
// Document Attachment Type
// ============================================================

export interface DocumentAttachment {
  name: string;
  url: string;
  mimeType?: string; // 'application/pdf', 'image/png', etc.
  fileSize?: number; // bytes
  uploadedAt: string; // ISO date
  uploadedBy?: string;
}

// ============================================================
// DRILL LOG (Execution Record)
// ============================================================

export interface DrillParticipant {
  crewId: string;
  crewName: string;
  rank?: string;
  role?: string; // Role in the drill (e.g., "Team Leader", "Firefighter", "Observer")
  isNewCrew: boolean; // For *1 trigger detection (>25% turnover)
  performance?: string; // "EXCELLENT", "SATISFACTORY", "NEEDS_IMPROVEMENT"
}

export interface DrillLog {
  id: string;
  logCode: string; // e.g., "DL-20250124-FIRE_DRILL-abc123"
  drillScheduleId?: string;
  drillTypeId: string;
  drillType?: DrillType;
  drillSchedule?: DrillSchedule;
  
  executionDate: string; // ISO date
  executionTime?: string; // Time of day
  duration?: number; // In minutes
  location?: string; // "Engine Room", "Bridge", "Accommodation", etc.
  weatherCondition?: string; // "CALM", "ROUGH", "HEAVY_WEATHER"
  result: DrillResult;
  overallAssessment?: string;
  
  // Participants (deserialized from JSONB)
  participants: DrillParticipant[];
  totalParticipants: number;
  newCrewCount: number; // For *1 trigger rule (>25% turnover)
  
  // Observations
  findings?: string; // What went well
  correctiveActions?: string; // What needs improvement
  generalRemarks?: string;
  lessonsLearned?: string;
  
  // Approval workflow (Master approval required per SOLAS)
  conductedByCrewId: string;
  conductedByCrewName?: string; // CrewMember.FullName
  verifiedByCrewId?: string; // Master approval
  verifiedByCrewName?: string; // Master name (CrewMember.FullName)
  verifiedDate?: string;
  isLocked: boolean; // True after Master approval (no further edits allowed)
  
  // Attachments
  attachmentUrls: string[]; // List of URLs (photos, videos, documents)
  
  vesselId?: string;
  originNode?: string; // "EDGE" or "SHORE"
  isSynced: boolean;
  createdAt: string;
  updatedAt?: string;
}

// ============================================================
// DTOs FOR API REQUESTS & RESPONSES
// ============================================================

/**
 * Request DTO for creating/updating drill schedule (from Edit Modal - Ảnh 3)
 */
export interface CreateUpdateDrillScheduleDto {
  drillTypeId: string;
  description?: string; // "Description" field in Ảnh 3
  category?: DrillCategory; // "Category" dropdown in Ảnh 3
  
  // "Type" radio buttons: Interval / One-time
  isInterval: boolean;
  intervalValue?: number; // "1" in example
  intervalUnit?: 'days' | 'weeks' | 'months' | 'years'; // "months" in example
  
  // Date fields
  startDate: string; // "24/05/2025" in Ảnh 3
  dueDate: string; // "24/06/2025" in Ảnh 3
  beforeDueDays: number; // "7" in "Before due" field
  
  // Checkboxes from right side of Ảnh 3
  hasNoExpiry: boolean; // "No expiry" checkbox
  isFixedInterval: boolean; // "Fixed intervals" checkbox
  isDocumentRequired: boolean; // "Document is required" checkbox
  isSecureHistory: boolean; // "Secure history" checkbox
  isCrewMemberRequired: boolean; // "Crew Member Required" checkbox
  isMandatorySignOnEvaluation: boolean; // "Mandatory sign on evaluation" checkbox
  
  // Rich text from "Data card" tab
  instructionContent?: string; // HTML content from rich text editor
  
  assignedToCrewId?: string;
  remarks?: string;
  
  // Participants - array of crew member IDs (only when isCrewMemberRequired = true)
  participants?: string[];
  
  // Documents/Attachments
  documents?: DocumentAttachment[];
}

/**
 * Request DTO for creating drill log (recording execution)
 */
export interface CreateDrillLogDto {
  drillScheduleId?: string;
  drillTypeId: string;
  executionDate: string;
  executionTime?: string;
  duration?: number;
  location?: string;
  weatherCondition?: string;
  result: DrillResult;
  overallAssessment?: string;
  
  participants: DrillParticipant[];
  
  findings?: string;
  correctiveActions?: string;
  generalRemarks?: string;
  lessonsLearned?: string;
  
  conductedByCrewId: string;
  attachmentUrls?: string[];
}

/**
 * Request DTO for Master approval
 */
export interface ApproveDrillLogDto {
  verifiedByCrewId: string; // Master crew ID
  approvalRemarks?: string;
}

/**
 * Query parameters for timeline view (Ảnh 2 filters)
 */
export interface DrillTimelineQueryDto {
  year?: number;
  month?: number;
  category?: DrillCategory;
  status?: DrillScheduleStatus;
  assignedToCrewId?: string;
  showOverdueOnly?: boolean;
  startDate?: string;
  endDate?: string;
}

/**
 * Response DTO for timeline grouped view (tree structure in Ảnh 2)
 */
export interface DrillTimelineGroupDto {
  category: DrillCategory;
  categoryDisplayName: string; // "Drills", "Work Permits", "Safety committee"
  totalDrills: number;
  completedCount: number;
  overdueCount: number;
  isExpanded: boolean; // For collapsible tree view
  schedules: DrillSchedule[]; // Timeline bars
}

/**
 * Statistics for dashboard/summary
 */
export interface DrillStatistics {
  totalScheduled: number;
  totalCompleted: number;
  totalOverdue: number;
  totalUpcoming: number; // Next 30 days
  complianceRate: number; // (completed/scheduled) * 100
  
  byCategory: Record<DrillCategory, number>; // Count per category
  byStatus: Record<DrillScheduleStatus, number>; // Count per status
  
  upcomingDrills: DrillSchedule[]; // Next 7 days
  overdueDrills: DrillSchedule[]; // All overdue
}

// ============================================================
// UI-SPECIFIC TYPES
// ============================================================

/**
 * Timeline bar color mapping (from Ảnh 2)
 */
export type TimelineBarColor = 'red' | 'green' | 'yellow' | 'blue';

export interface TimelineBarStyle {
  color: TimelineBarColor;
  label: string; // "2 w", "3 m", "-2 d", "6 d"
  startX: number; // Position in timeline (calculated from startDate)
  width: number; // Width in pixels (calculated from startDate to dueDate)
}

/**
 * Category display names for tree view (Ảnh 2)
 */
export const DRILL_CATEGORY_NAMES: Record<DrillCategory, string> = {
  STATION_DRILLS: 'Station Drills',
  EXERCISES: 'Exercises',
  EDUCATION: 'Education',
  TRAINING: 'Training',
  CHECKS: 'Checks',
  ISPS: 'ISPS Security'
};

/**
 * Status color mapping
 */
export const DRILL_STATUS_COLORS: Record<DrillScheduleStatus, TimelineBarColor> = {
  SCHEDULED: 'blue',
  DUE: 'yellow',
  OVERDUE: 'red',
  COMPLETED: 'green',
  CANCELLED: 'yellow'
};
