namespace MaritimeEdge.Constants;

/// <summary>
/// Department constants for crew organization and equipment grouping
/// Based on maritime vessel organizational structure
/// </summary>
public static class Department
{
    /// <summary>
    /// Engine Department - Bộ phận Máy
    /// Responsible for: Main Engine, Generators, Pumps, Boilers, HVAC
    /// Leadership: C/E → 2/E (Work Planner) → 3/E → 4/E → E/O → Fitters/Oilers
    /// </summary>
    public const string ENGINE = "ENGINE";
    
    /// <summary>
    /// Deck Department - Bộ phận Boong
    /// Responsible for: Hull, Cargo, LSA, FSS, Deck Machinery
    /// Leadership: C/O (Work Planner) → 2/O → 3/O → Bosun → AB/OS
    /// </summary>
    public const string DECK = "DECK";
    
    /// <summary>
    /// Navigation Department - Bộ phận Hàng hải
    /// Responsible for: Bridge equipment, Navigation systems, Communication
    /// Leadership: Master → C/O → 2/O (Primary) → 3/O
    /// </summary>
    public const string NAVIGATION = "NAVIGATION";
    
    /// <summary>
    /// Management Level - Cấp quản lý
    /// Master, C/E - Approval and oversight only
    /// </summary>
    public const string MANAGEMENT = "MANAGEMENT";
    
    /// <summary>
    /// Electrical - Bộ phận Điện (can be independent or under ENGINE)
    /// Responsible for: Electrical systems, Automation
    /// Leadership: E/O → reports to C/E
    /// </summary>
    public const string ELECTRICAL = "ELECTRICAL";
    
    /// <summary>
    /// Catering Department - Bộ phận Ăn uống
    /// Responsible for: Food service, Galley equipment
    /// </summary>
    public const string CATERING = "CATERING";
}

/// <summary>
/// Task status including approval workflow
/// Extended status workflow for maritime PMS
/// </summary>
public static class TaskStatusExtended
{
    /// <summary>
    /// Initial status when task is auto-generated by scheduler
    /// Task may be incomplete (no assignment, missing info)
    /// Work Planner reviews and assigns before moving to PENDING or PENDING_APPROVAL
    /// </summary>
    public const string TASK = "TASK";
    
    /// <summary>
    /// Task is ready for execution (fully assigned, approved if needed)
    /// Visible on mobile app for crew to start work
    /// </summary>
    public const string PENDING = "PENDING";
    
    /// <summary>
    /// Task waiting for C/E or C/O approval before execution
    /// Used for HIGH/CRITICAL priority tasks with full assignment
    /// </summary>
    public const string PENDING_APPROVAL = "PENDING_APPROVAL";
    
    /// <summary>
    /// Task rejected by approver, needs revision
    /// Work Planner must review and fix before resubmitting
    /// </summary>
    public const string REJECTED = "REJECTED";
    
    /// <summary>
    /// Task is past due date, requires immediate attention
    /// Can be in any assignment state
    /// </summary>
    public const string OVERDUE = "OVERDUE";
    
    /// <summary>
    /// Task execution started by crew (mobile app)
    /// </summary>
    public const string IN_PROGRESS = "IN_PROGRESS";
    
    /// <summary>
    /// Task completed successfully
    /// </summary>
    public const string COMPLETED = "COMPLETED";
}
